review fixes

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,4 +1,11 @@
 #!/bin/bash
 
-exec python tests.py
+python tests.py
+OUT=$?
+echo $OUT
+if [ $OUT -eq 0 ];then
+   exit 0
+else
+   echo "Unit test failed, fix it"
+   exit 1
 fi
